package enums;

public enum CaliforniaStylePizzaEnums {
    CALIFORNIA_STYLE_CHEESE_PIZZA,
    CALIFORNIA_STYLE_PEPPERONI_PIZZA,
    CALIFORNIA_STYLE_CLAM_PIZZA,
    CALIFORNIA_STYLE_VEGGIE_PIZZA,
    CALIFORNIA_STYLE_DEFAULT_PIZZA
}
