package enums;

public enum ChicagoStylePizzaEnums {
    CHICAGO_STYLE_CHEESE_PIZZA,
    CHICAGO_STYLE_PEPPERONI_PIZZA,
    CHICAGO_STYLE_CLAM_PIZZA,
    CHICAGO_STYLE_VEGGIE_PIZZA,
    CHICAGO_STYLE_DEFAULT_PIZZA
}
